### PR TITLE
ticketmaster search router and controller

### LINKED ISSUE #16: Ticketmaster Search Router

### LINKED ISSUE #17: Ticketmaster Search Controller

### PR DESCRIPTION
**Pull request by AmandaHockmuth**
Installed axios, added ticketmaster router and controller.

### CODE REVIEW

**Comment by StuvaScript** [comment]
Great work Amanda! So in order to get this to play nicely with front end and to work, I needed to do a few things:

- In ticketmasterRouter.js:
  - I defined the route as "/events/:city/:stateCode/:startDateTime?/:endDateTime?" without the leading "/api" because "/api" is already handled by app.use("/api", ticketmasterRouter) in app.js.

- I needed to install dotenv even though I think I already saw it as a dependency.

- In app.js:
  - I needed to add "require("dotenv").config();" to the very top of the page import the dotenv package.
  
  Let me know your thoughts!

**Comment by StuvaScript** [comment]
Also on the front end when I add an endDate but leave out the startDate, the API response actually comes back with a search based on a startDate with no endDate. Instead of all the params being in the url, is there a way we could send a params object to the backend with key value pairs?

Example:

```javascript
// params object
{
city: "Seattle",
stateCode: "WA",
startDateTime: "", // <-- optional
endDateTime: "2025-02-25" // <-- optional
}
```

**Review by jgoldenberg29 — APPROVED** [review]
Very nicely done with the ticket master fetch function! Very systematic and well implemented.

**Comment by StuvaScript** [comment]
So with the help of chatGPT, I found out how to make the startDateTime and endDateTime optional. On my end I would pass them in as a param object in the GET request while the city and stateCode would still get passed in the url as they are manditory. 

For the back end, in the ticketmasterController.js: 

Shortened the req.params to only call city and stateCode. Added a req.query and have it recieve the startDateTime and endDateTime.

  // const { city, stateCode, startDateTime, endDateTime } = req.params; // <-- removed

  const { city, stateCode } = req.params; // <-- added
  const { startDateTime, endDateTime } = req.query; // <-- added
  
  Lemme know your thoughts!!

**Comment by AmandaHockmuth** [comment]
Good catches Stu!
Those all sound like solid changes to me, are those things you've already implemented locally? You're welcome to push them up to this branch and we can have Josh take a final look before we publish to main?

**Comment by StuvaScript** [comment]
Just waiting on the merge of my branch with the edits and this branch should be good to go!

**Review by jgoldenberg29 — APPROVED** [review]
great collab!

**Review by StuvaScript — APPROVED** [review]
Merged in my updates and everything looks good to go!!

**Pull request merged**
